name: Format Backend
on: pull_request

jobs:
  python-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x' 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      
      - name: Format python files
        run: |
          black backend/
      
      - name: Commit all changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: "UFC_AUTOBOTS"
          commit_message: Aply formatting changes
          branch: ${{ github.head_ref }}